name: Continuous Integration
on: push

jobs:
  build:
    name: Build bazel-remote-cache
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: bazel build --host_force_python=PY2 -c opt //:bazel-remote-image
